"""
patch_thermal_autoload.py
=========================
Adds auto-load feature to the Thermal tab in app.py.
Instead of manually uploading files every time, user points to the
thermal_results folder generated by batch_thermal_run.py and
results load instantly — same as ECM batch_run.py workflow.

Run from your project folder: python patch_thermal_autoload.py
"""
import shutil, os

APP = "app.py"
if not os.path.isfile(APP):
    print("[ERROR] app.py not found"); exit(1)

shutil.copy2(APP, APP + ".autoload_bak")

with open(APP, "r", encoding="utf-8") as f:
    src = f.read()

ok = 0

# ══════════════════════════════════════════════════════════════════════════════
# PATCH: Replace the top of the thermal tab (the file uploader section)
# with a tabbed interface: "Auto Load" (from batch results) + "Manual Upload"
# ══════════════════════════════════════════════════════════════════════════════

# Find the anchor — the thermal tab starts with this header
OLD_TOP = '''    elif _sel == "Thermal":
        st.markdown("""
        <div class="glass-panel" style="border-color:rgba(255,136,0,0.4);">
          <h3 style="font-size:1.3rem;margin-bottom:4px;">🌡️ LUMPED THERMAL MODEL</h3>
          <p style="font-family:'Share Tech Mono',monospace;font-size:0.75rem;color:#5a7090;margin-top:0;letter-spacing:0.1em;">
            Calibrate C_th &amp; hA from charge data · Validate on unseen profiles · Discrete state-space thermal equation
          </p>
        </div>""", unsafe_allow_html=True)

        # ── File uploaders ───────────────────────────────────────────────────
        th_c1, th_c2 = st.columns(2, gap="large")
        with th_c1:
            st.markdown("""<div class="glass-panel"><h4 style="font-size:1.05rem;margin:0;">📂 CALIBRATION FILES</h4>
            <p style="font-family:'Share Tech Mono',monospace;font-size:0.72rem;color:#5a7090;margin:4px 0 0;">
            Upload charge CSV files · model fits C_th &amp; hA</p></div>""", unsafe_allow_html=True)
            th_calib_files = st.file_uploader(
                "Upload Calibration CSVs", type=["csv"],
                accept_multiple_files=True, key="th_calib_upload",
                label_visibility="collapsed")

        with th_c2:
            st.markdown("""<div class="glass-panel"><h4 style="font-size:1.05rem;margin:0;">📂 VALIDATION FILES</h4>
            <p style="font-family:'Share Tech Mono',monospace;font-size:0.72rem;color:#5a7090;margin:4px 0 0;">
            Upload validation CSVs · same C_th &amp; hA, no re-tuning</p></div>""", unsafe_allow_html=True)
            th_valid_files = st.file_uploader(
                "Upload Validation CSVs", type=["csv"],
                accept_multiple_files=True, key="th_valid_upload",
                label_visibility="collapsed")'''

NEW_TOP = '''    elif _sel == "Thermal":
        st.markdown("""
        <div class="glass-panel" style="border-color:rgba(255,136,0,0.4);">
          <h3 style="font-size:1.3rem;margin-bottom:4px;">🌡️ LUMPED THERMAL MODEL</h3>
          <p style="font-family:'Share Tech Mono',monospace;font-size:0.75rem;color:#5a7090;margin-top:0;letter-spacing:0.1em;">
            Calibrate C_th &amp; hA from charge data · Validate on unseen profiles · Discrete state-space thermal equation
          </p>
        </div>""", unsafe_allow_html=True)

        # ── Load mode selector ───────────────────────────────────────────────
        th_mode = st.radio(
            "Load Mode", ["⚡ Auto Load (from batch results)", "📂 Manual Upload"],
            horizontal=True, key="th_load_mode", label_visibility="collapsed")

        st.markdown("<div style='height:8px'></div>", unsafe_allow_html=True)

        th_calib_files = []
        th_valid_files = []

        if th_mode == "⚡ Auto Load (from batch results)":
            # ── Auto Load UI ─────────────────────────────────────────────────
            st.markdown("""
            <div class="glass-panel" style="border-color:rgba(255,136,0,0.3);">
              <h4 style="font-size:1.05rem;margin:0 0 6px;">⚡ AUTO LOAD — Batch Results Folder</h4>
              <p style="font-family:'Share Tech Mono',monospace;font-size:0.72rem;color:#5a7090;margin:0;letter-spacing:0.1em;">
                Point to the thermal_results folder generated by batch_thermal_run.py
              </p>
            </div>""", unsafe_allow_html=True)

            al1, al2 = st.columns([3, 1], gap="medium")
            with al1:
                results_folder = st.text_input(
                    "Results Folder Path",
                    value=st.session_state.get("th_results_folder", ""),
                    placeholder="e.g.  Battery47/charge/thermal_results",
                    key="th_results_folder_input",
                    label_visibility="collapsed")
            with al2:
                load_btn = st.button("📂 LOAD RESULTS", use_container_width=True,
                                     key="th_load_btn")

            if load_btn and results_folder:
                import glob as _glob
                params_path = os.path.join(results_folder, "thermal_params.csv")
                calib_summary = os.path.join(results_folder, "batch_thermal_summary.csv")
                valid_summary = os.path.join(results_folder, "batch_valid_summary.csv")

                if not os.path.isfile(params_path):
                    st.error(f"thermal_params.csv not found in: {results_folder}")
                else:
                    import pandas as _pd
                    import numpy as _np

                    p = _pd.read_csv(params_path).iloc[0]
                    C_th_loaded = float(p["C_th_J_K"])
                    hA_loaded   = float(p["hA_W_K"])
                    T_amb_loaded = float(p["T_amb_C"])
                    R_loaded    = float(p["R_ohm"])
                    n_files     = int(p.get("n_calib_files", 0))

                    # Load best calibration file prediction
                    best_file   = str(p.get("best_file", "")).replace(".csv", "_thermal.csv")
                    best_pred   = os.path.join(results_folder, best_file)

                    if os.path.isfile(best_pred):
                        df_pred = _pd.read_csv(best_pred)
                        T_meas  = df_pred["T_meas_C"].tolist()
                        T_pred  = df_pred["T_pred_C"].tolist()
                        time_v  = df_pred["Time_s"].tolist()

                        # Recompute metrics
                        err = _np.array(T_meas) - _np.array(T_pred)
                        rmse = float(_np.sqrt(_np.mean(err**2)))
                        mae  = float(_np.mean(_np.abs(err)))
                        ss_res = _np.sum(err**2)
                        ss_tot = _np.sum((_np.array(T_meas) - _np.mean(T_meas))**2)
                        r2   = float(1 - ss_res / (ss_tot + 1e-12))
                        maxe = float(_np.max(_np.abs(err)))
                        mape = float(_np.mean(_np.abs(err) / (_np.abs(_np.array(T_meas)) + 1e-6)) * 100)

                        metrics = dict(RMSE_C=rmse, MAE_C=mae, R2=r2, MaxErr_C=maxe, MAPE_pct=mape)

                        st.session_state["thermal_results"] = {
                            "C_th": C_th_loaded, "C_th_final": C_th_loaded,
                            "hA":   hA_loaded,   "hA_final":   hA_loaded,
                            "T_amb": T_amb_loaded, "R_ohm": R_loaded,
                            "time": time_v, "T_measured": T_meas, "T_predicted": T_pred,
                            "metrics": metrics,
                        }
                        st.session_state["th_results_folder"] = results_folder
                    else:
                        # No best prediction file — just store params with dummy arrays
                        st.session_state["thermal_results"] = {
                            "C_th": C_th_loaded, "C_th_final": C_th_loaded,
                            "hA":   hA_loaded,   "hA_final":   hA_loaded,
                            "T_amb": T_amb_loaded, "R_ohm": R_loaded,
                            "time": [], "T_measured": [], "T_predicted": [],
                            "metrics": dict(RMSE_C=0, MAE_C=0, R2=0, MaxErr_C=0, MAPE_pct=0),
                        }
                        st.session_state["th_results_folder"] = results_folder

                    # Load validation results if available
                    if os.path.isfile(valid_summary):
                        vs = _pd.read_csv(valid_summary)
                        best_v = vs.loc[vs["RMSE_C"].idxmin()]
                        vfile  = str(best_v["File"]).replace(".csv", "_valid.csv")
                        vpath  = os.path.join(results_folder, vfile)
                        if os.path.isfile(vpath):
                            dv = _pd.read_csv(vpath)
                            tv_meas = dv["T_meas_C"].tolist()
                            tv_pred = dv["T_pred_C"].tolist()
                            tv_time = dv["Time_s"].tolist()
                            verr = _np.array(tv_meas) - _np.array(tv_pred)
                            v_metrics = dict(
                                RMSE_C=float(_np.sqrt(_np.mean(verr**2))),
                                MAE_C=float(_np.mean(_np.abs(verr))),
                                R2=float(1 - _np.sum(verr**2) / (_np.sum((_np.array(tv_meas)-_np.mean(tv_meas))**2)+1e-12)),
                                MaxErr_C=float(_np.max(_np.abs(verr))),
                                MAPE_pct=float(_np.mean(_np.abs(verr)/(_np.abs(_np.array(tv_meas))+1e-6))*100),
                            )
                            st.session_state["thermal_valid_results"] = {
                                "C_th": C_th_loaded, "hA": hA_loaded,
                                "T_amb": T_amb_loaded, "R_ohm": R_loaded,
                                "time": tv_time, "T_measured": tv_meas, "T_predicted": tv_pred,
                                "metrics": v_metrics,
                            }

                    st.success(f"✅ Loaded: C_th={C_th_loaded:.1f} J/K  hA={hA_loaded:.5f} W/K  "
                               f"R={R_loaded*1000:.1f} mΩ  ({n_files} calibration files)")
                    st.rerun()

            # Show current loaded state
            _th_loaded = st.session_state.get("thermal_results")
            if _th_loaded and results_folder:
                st.markdown(f"""
                <div style="background:rgba(0,255,136,0.06);border:2px solid rgba(0,255,136,0.3);
                            border-radius:14px;padding:16px 20px;margin-top:12px;">
                  <div style="font-family:'Orbitron',monospace;color:#00cc66;font-size:0.72rem;
                              font-weight:700;letter-spacing:0.12em;margin-bottom:8px;">
                    ✅ RESULTS LOADED</div>
                  <div style="display:flex;gap:32px;flex-wrap:wrap;">
                    <span style="font-family:Share Tech Mono,monospace;color:#2a4060;font-size:0.82rem;">
                      C_th = <b style="color:#ff8800;">{_th_loaded['C_th']:.1f} J/K</b></span>
                    <span style="font-family:Share Tech Mono,monospace;color:#2a4060;font-size:0.82rem;">
                      hA = <b style="color:#cc44ff;">{_th_loaded['hA']:.5f} W/K</b></span>
                    <span style="font-family:Share Tech Mono,monospace;color:#2a4060;font-size:0.82rem;">
                      R = <b style="color:#00c8ff;">{_th_loaded['R_ohm']*1000:.1f} mΩ</b></span>
                    <span style="font-family:Share Tech Mono,monospace;color:#2a4060;font-size:0.82rem;">
                      RMSE = <b style="color:#00ff88;">{_th_loaded['metrics']['RMSE_C']:.4f} C</b></span>
                  </div>
                </div>""", unsafe_allow_html=True)

        else:
            # ── Manual Upload UI ─────────────────────────────────────────────
            th_c1, th_c2 = st.columns(2, gap="large")
            with th_c1:
                st.markdown("""<div class="glass-panel"><h4 style="font-size:1.05rem;margin:0;">📂 CALIBRATION FILES</h4>
                <p style="font-family:'Share Tech Mono',monospace;font-size:0.72rem;color:#5a7090;margin:4px 0 0;">
                Upload charge CSV files · model fits C_th &amp; hA</p></div>""", unsafe_allow_html=True)
                th_calib_files = st.file_uploader(
                    "Upload Calibration CSVs", type=["csv"],
                    accept_multiple_files=True, key="th_calib_upload",
                    label_visibility="collapsed")

            with th_c2:
                st.markdown("""<div class="glass-panel"><h4 style="font-size:1.05rem;margin:0;">📂 VALIDATION FILES</h4>
                <p style="font-family:'Share Tech Mono',monospace;font-size:0.72rem;color:#5a7090;margin:4px 0 0;">
                Upload validation CSVs · same C_th &amp; hA, no re-tuning</p></div>""", unsafe_allow_html=True)
                th_valid_files = st.file_uploader(
                    "Upload Validation CSVs", type=["csv"],
                    accept_multiple_files=True, key="th_valid_upload",
                    label_visibility="collapsed")'''

if OLD_TOP in src:
    src = src.replace(OLD_TOP, NEW_TOP, 1)
    print("[OK] Thermal tab auto-load feature added")
    ok += 1
else:
    print("[!] Anchor not found — searching for thermal tab header...")
    for i, line in enumerate(src.splitlines()):
        if 'elif _sel == "Thermal"' in line:
            print(f"  Line {i+1}: {line.strip()}")
        if 'th_calib_upload' in line:
            print(f"  Line {i+1}: {line.strip()[:80]}")

# Also add os import if not present
if "import os" not in src:
    src = src.replace("import streamlit as st", "import os\nimport streamlit as st", 1)
    print("[OK] import os added")

with open(APP, "w", encoding="utf-8") as f:
    f.write(src)

print(f"\n[{'DONE' if ok else 'FAILED'}]")
if ok:
    print("""
COMPLETE WORKFLOW:
─────────────────
Step 1 — Convert XLS to CSV (one time only):
    python xls_to_csv.py --folder "Battery47/charge"   --out "Battery47/charge_csv"
    python xls_to_csv.py --folder "Battery47/discharge" --out "Battery47/discharge_csv"

Step 2 — Run batch thermal calibration + validation:
    python batch_thermal_run.py --calib "Battery47/charge_csv" --valid "Battery47/discharge_csv"
    (Results saved to Battery47/charge_csv/thermal_results/)

Step 3 — In the app:
    Models tab → Thermal Simulation
    Simulation tab → select "Auto Load"
    Paste path:  Battery47/charge_csv/thermal_results
    Click LOAD RESULTS → done instantly, no file uploading needed
""")