"""
patch_autoload_v3.py
====================
Adds auto-load feature to the Thermal tab using exact anchor text.
Run from your project folder: python patch_autoload_v3.py
"""
import shutil

APP = "app.py"
shutil.copy2(APP, APP + ".al3_bak")

with open(APP, "r", encoding="utf-8") as f:
    src = f.read()

OLD = """        cal_col, val_col = st.columns(2)
        with cal_col:
            st.markdown(\"\"\"
            <div class="glass-panel" style="border-color:rgba(255,136,0,0.4);">
              <h4 style="color:#cc6600;font-size:1.05rem;margin:0 0 4px;">CALIBRATION FILES</h4>
              <p style="font-family:'Share Tech Mono',monospace;font-size:0.72rem;color:#5a7090;margin:0;">
                Upload NASA Charge CSV files. C_th and hA estimated here.
              </p>
            </div>\"\"\", unsafe_allow_html=True)
            calib_files = st.file_uploader(
                "Calibration Charge CSVs",
                type=["csv"],
                accept_multiple_files=True,
                key="thermal_calib_uploader",
                label_visibility="collapsed",
            )

        with val_col:
            st.markdown(\"\"\"
            <div class="glass-panel" style="border-color:rgba(204,68,255,0.4);">
              <h4 style="color:#9933cc;font-size:1.05rem;margin:0 0 4px;">VALIDATION FILES</h4>
              <p style="font-family:'Share Tech Mono',monospace;font-size:0.72rem;color:#5a7090;margin:0;">
                Upload CSV files with Temperature_measured. Same C_th/hA, no re-tuning.
              </p>
            </div>\"\"\", unsafe_allow_html=True)
            valid_files = st.file_uploader(
                "Validation CSVs",
                type=["csv"],
                accept_multiple_files=True,
                key="thermal_valid_uploader",
                label_visibility="collapsed",
            )"""

NEW = """        th_mode = st.radio(
            "Load Mode", ["⚡ Auto Load (from batch results)", "📂 Manual Upload"],
            horizontal=True, key="th_load_mode", label_visibility="collapsed")

        st.markdown("<div style='height:8px'></div>", unsafe_allow_html=True)

        calib_files = []
        valid_files = []

        if th_mode == "⚡ Auto Load (from batch results)":
            st.markdown(\"\"\"
            <div class="glass-panel" style="border-color:rgba(255,136,0,0.3);">
              <h4 style="font-size:1.05rem;margin:0 0 6px;">⚡ AUTO LOAD — Batch Results Folder</h4>
              <p style="font-family:'Share Tech Mono',monospace;font-size:0.72rem;color:#5a7090;margin:0;">
                Point to the thermal_results folder generated by batch_thermal_run.py
              </p>
            </div>\"\"\", unsafe_allow_html=True)

            al1, al2 = st.columns([3, 1], gap="medium")
            with al1:
                results_folder = st.text_input(
                    "Results Folder Path",
                    value=st.session_state.get("th_results_folder", ""),
                    placeholder="e.g.  Battery47/discharge/thermal_results",
                    key="th_results_folder_input",
                    label_visibility="collapsed")
            with al2:
                load_btn = st.button("📂 LOAD RESULTS", use_container_width=True, key="th_load_btn")

            if load_btn and results_folder:
                import pandas as _pd
                import numpy as _np
                params_path   = os.path.join(results_folder, "thermal_params.csv")
                valid_summary = os.path.join(results_folder, "batch_valid_summary.csv")
                if not os.path.isfile(params_path):
                    st.error(f"thermal_params.csv not found in: {results_folder}")
                else:
                    p = _pd.read_csv(params_path).iloc[0]
                    C_th_l  = float(p["C_th_J_K"])
                    hA_l    = float(p["hA_W_K"])
                    T_amb_l = float(p["T_amb_C"])
                    R_l     = float(p["R_ohm"])
                    n_files = int(p.get("n_calib_files", 0))
                    best_file_raw = str(p.get("best_file", ""))
                    # Build prediction file path
                    if "/" in best_file_raw:
                        parts = best_file_raw.split("/")
                        pred_fname = f"{parts[0]}_{parts[1].replace('.csv','_thermal.csv')}"
                    else:
                        pred_fname = best_file_raw.replace(".csv", "_thermal.csv")
                    best_pred = os.path.join(results_folder, pred_fname)
                    if os.path.isfile(best_pred):
                        df_pred = _pd.read_csv(best_pred)
                        T_meas = df_pred["T_meas_C"].tolist()
                        T_pred = df_pred["T_pred_C"].tolist()
                        time_v = df_pred["Time_s"].tolist()
                        err    = _np.array(T_meas) - _np.array(T_pred)
                        rmse   = float(_np.sqrt(_np.mean(err**2)))
                        mae    = float(_np.mean(_np.abs(err)))
                        ss_res = _np.sum(err**2)
                        ss_tot = _np.sum((_np.array(T_meas) - _np.mean(T_meas))**2)
                        r2     = float(1 - ss_res / (ss_tot + 1e-12))
                        metrics = dict(RMSE_C=rmse, MAE_C=mae, R2=r2,
                                       MaxErr_C=float(_np.max(_np.abs(err))),
                                       MAPE_pct=float(_np.mean(_np.abs(err)/(_np.abs(_np.array(T_meas))+1e-6))*100))
                    else:
                        time_v, T_meas, T_pred = [], [], []
                        metrics = dict(RMSE_C=0, MAE_C=0, R2=0, MaxErr_C=0, MAPE_pct=0)
                    st.session_state["thermal_results"] = {
                        "C_th": C_th_l, "C_th_final": C_th_l,
                        "hA":   hA_l,   "hA_final":   hA_l,
                        "T_amb": T_amb_l, "R_ohm": R_l,
                        "time": time_v, "T_measured": T_meas,
                        "T_predicted": T_pred, "metrics": metrics,
                        "params": {"R0_ohm": R_l},
                    }
                    st.session_state["th_results_folder"] = results_folder
                    # Load validation results if available
                    if os.path.isfile(valid_summary):
                        vs = _pd.read_csv(valid_summary)
                        best_v = vs.loc[vs["RMSE_C"].idxmin()]
                        vfolder = str(best_v.get("Folder", "discharge"))
                        vfile   = str(best_v["File"]).replace(".csv", "_valid.csv")
                        vpath   = os.path.join(results_folder, f"{vfolder}_{vfile}")
                        if os.path.isfile(vpath):
                            dv   = _pd.read_csv(vpath)
                            tv_m = dv["T_meas_C"].tolist()
                            tv_p = dv["T_pred_C"].tolist()
                            tv_t = dv["Time_s"].tolist()
                            verr = _np.array(tv_m) - _np.array(tv_p)
                            st.session_state["thermal_valid_results"] = {
                                "C_th": C_th_l, "hA": hA_l,
                                "T_amb": T_amb_l, "R_ohm": R_l,
                                "time": tv_t, "T_measured": tv_m, "T_predicted": tv_p,
                                "metrics": dict(
                                    RMSE_C=float(_np.sqrt(_np.mean(verr**2))),
                                    MAE_C=float(_np.mean(_np.abs(verr))),
                                    R2=float(1-_np.sum(verr**2)/(_np.sum((_np.array(tv_m)-_np.mean(tv_m))**2)+1e-12)),
                                    MaxErr_C=float(_np.max(_np.abs(verr))),
                                    MAPE_pct=float(_np.mean(_np.abs(verr)/(_np.abs(_np.array(tv_m))+1e-6))*100))}
                            }
                    st.success(f"✅ Loaded: C_th={C_th_l:.1f} J/K  hA={hA_l:.5f} W/K  R={R_l*1000:.1f} mΩ  ({n_files} files)")
                    st.rerun()

            _th_loaded = st.session_state.get("thermal_results")
            if _th_loaded:
                st.markdown(f\"\"\"
                <div style="background:rgba(0,255,136,0.06);border:2px solid rgba(0,255,136,0.3);
                            border-radius:14px;padding:16px 20px;margin-top:12px;">
                  <div style="font-family:'Orbitron',monospace;color:#00cc66;font-size:0.72rem;
                              font-weight:700;letter-spacing:0.12em;margin-bottom:8px;">✅ RESULTS LOADED</div>
                  <div style="display:flex;gap:32px;flex-wrap:wrap;">
                    <span style="font-family:Share Tech Mono,monospace;color:#2a4060;font-size:0.82rem;">
                      C_th = <b style="color:#ff8800;">{_th_loaded['C_th']:.1f} J/K</b></span>
                    <span style="font-family:Share Tech Mono,monospace;color:#2a4060;font-size:0.82rem;">
                      hA = <b style="color:#cc44ff;">{_th_loaded['hA']:.5f} W/K</b></span>
                    <span style="font-family:Share Tech Mono,monospace;color:#2a4060;font-size:0.82rem;">
                      RMSE = <b style="color:#00ff88;">{_th_loaded['metrics']['RMSE_C']:.4f} °C</b></span>
                  </div>
                </div>\"\"\", unsafe_allow_html=True)

        else:
            cal_col, val_col = st.columns(2)
            with cal_col:
                st.markdown(\"\"\"
                <div class="glass-panel" style="border-color:rgba(255,136,0,0.4);">
                  <h4 style="color:#cc6600;font-size:1.05rem;margin:0 0 4px;">CALIBRATION FILES</h4>
                  <p style="font-family:'Share Tech Mono',monospace;font-size:0.72rem;color:#5a7090;margin:0;">
                    Upload NASA Charge CSV files. C_th and hA estimated here.
                  </p>
                </div>\"\"\", unsafe_allow_html=True)
                calib_files = st.file_uploader(
                    "Calibration Charge CSVs",
                    type=["csv"],
                    accept_multiple_files=True,
                    key="thermal_calib_uploader",
                    label_visibility="collapsed",
                )

            with val_col:
                st.markdown(\"\"\"
                <div class="glass-panel" style="border-color:rgba(204,68,255,0.4);">
                  <h4 style="color:#9933cc;font-size:1.05rem;margin:0 0 4px;">VALIDATION FILES</h4>
                  <p style="font-family:'Share Tech Mono',monospace;font-size:0.72rem;color:#5a7090;margin:0;">
                    Upload CSV files with Temperature_measured. Same C_th/hA, no re-tuning.
                  </p>
                </div>\"\"\", unsafe_allow_html=True)
                valid_files = st.file_uploader(
                    "Validation CSVs",
                    type=["csv"],
                    accept_multiple_files=True,
                    key="thermal_valid_uploader",
                    label_visibility="collapsed",
                )"""

if OLD in src:
    src = src.replace(OLD, NEW, 1)
    print("[OK] Auto-load feature added successfully")
    with open(APP, "w", encoding="utf-8") as f:
        f.write(src)
    print("\nRun:  streamlit run app.py")
    print("\nIn the app:")
    print("  Models tab → Thermal Simulation")
    print("  Simulation tab → ⚡ Auto Load")
    print("  Paste: Battery47/discharge/thermal_results")
    print("  Click LOAD RESULTS")
else:
    print("[FAILED] Anchor not found")
    print("Check that app.py has not been modified since last backup")